# Generated by Django 4.0.5 on 2022-06-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='direction',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='provider',
            name='imagen',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='provider',
            name='servicios',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='provider',
            name='telefono',
            field=models.CharField(default='', max_length=255),
        ),
    ]
