# Generated by Django 4.0.5 on 2022-06-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_provider_direction_provider_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imagen',
            field=models.CharField(default='', max_length=255),
        ),
    ]
